---
openapi: 3.0.2
info:
  title: service-groups-integrationV1
  version: 1.0.0
  description: |
    API de integração de grupos de produto (Service Groups) V1

    Compatível com a versão de negócio Product V7
  contact: {}
servers:
- url: https://{url}/api/{version}/integration
  description: Integration Router Server
  variables:
    url:
      default: app2.mastercrm.ws
      description: URL de acesso ao Integration-Router
    version:
      default: v1
      description: Versão do Integration-Router
paths:
  /record:
    summary: API de integração groups
    get:
      tags:
      - Service-Groups
      parameters:
      - name: Integration-Filter
        description: |
          Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
          RestQuery.


          Se o header for omitido, lista todos os registros

          Se o header não contiver valores, lista todos os registros
        schema:
          type: string
        in: header
        required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service-Groups-Integration_V1_GetResponse'
          description: Returns a list of service groups
        401:
          description: Unauthorized
      summary: Listar grupo de serviços
      description: Retorna uma lista de grupos de serviço cadastrados ou determinados
        grupos com base nos filtros do header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service-Groups-Integration_V1_BodyEmpty'
      tags:
      - Service-groups
      parameters:
      - name: Integration-Filter
        description: |
          Filtro do registro específico para a ação. Deve-se usar o identificador principal da
          entidade (ID).
        schema:
          type: string
        in: header
        required: false
      - name: Integration-Response
        description: |
          Nível de detalhe do retorno da API. São suportados atualmente:

          **full** - Resposta completa, equivalente a um GET no recurso

          **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
          registro

          Se o header não for informado, por padrão o retorno será equivalente ao nível
          **minimum**
        schema:
          enum:
          - full
          - minimum
          type: string
        in: header
        required: false
      - name: Integration-Action
        description: |
          Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
          body da requisição.
        schema:
          anyOf:
          - $ref: '#/components/schemas/Service-Groups-Integration_V1_BodyCreate'
          - $ref: '#/components/schemas/Service-Groups-Integration_V1_BodyUpdate'
          - $ref: '#/components/schemas/Service-Groups-Integration_V1_BodyUpsert'
          discriminator:
            mapping:
              create: '#/components/schemas/Service-Groups-Integration_V1_BodyCreate'
              update: '#/components/schemas/Service-Groups-Integration_V1_BodyUpdate'
              upsert: '#/components/schemas/Service-Groups-Integration_V1_BodyUpsert'
        in: header
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/Service-Groups-Integration_V1_FullResponse'
                - $ref: '#/components/schemas/Service-Groups-Integration_V1_MinimumResponse'
                discriminator:
                  mapping:
                    full: '#/components/schemas/Service-Groups-Integration_V1_FullResponse'
                    minimum: '#/components/schemas/Service-Groups-Integration_V1_MinimumResponse'
          description: Returns a service group register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar grupos de serviço
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;
    parameters:
    - name: Integration-Service
      description: 'Serviço responsável pela entidade. Exemplo: product'
      schema:
        default: product
        type: string
      in: header
      required: true
    - name: Integration-Resource
      description: 'Recurso para requisição. Exemplo: service-groups-integration'
      schema:
        default: service-groups-integration
        type: string
      in: header
      required: true
    - name: Integration-Version
      description: 'Versão da API de integração. Exemplo: v1'
      schema:
        default: v1
        type: string
      in: header
      required: true
components:
  schemas:
    Service-Groups-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Service-Groups-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Service-Groups-Integration_V1_BodyCreate:
      required:
      - active
      - description
      - externalId
      - code
      type: object
      properties:
        active:
          description: Define se o registro está ativo
          type: boolean
          example: true
        code:
          description: Código do grupo de produto
          type: string
          example: CONS
        description:
          description: Descrição do grupo de produto
          type: string
          example: Consultoria
        externalId:
          description: Código do sistema externo para identificação única do registro
          type: string
          example: Cons
        serviceGroupUpperId:
          description: Grupo de produto superior
          type: string
    Service-Groups-Integration_V1_BodyUpdate:
      type: object
      properties:
        active:
          type: boolean
          example: true
        code:
          type: string
          example: CONS
        description:
          type: string
          example: Consultoria
        externalId:
          type: string
          example: Cons
        serviceGroupUpperId:
          type: string
    Service-Groups-Integration_V1_BodyUpsert:
      type: object
      properties:
        active:
          type: boolean
          example: true
        code:
          type: string
          example: CONS
        description:
          type: string
          example: Consultoria
        externalId:
          type: string
          example: Cons
        serviceGroupUpperId:
          type: string
    Service-Groups-Integration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
          example: 02285a7b-de5e-460b-a19f-29ae81e1e3cb
        createdAt:
          type: string
          example: 2020-05-22T12:13:21.571Z
        updatedAt:
          type: string
          example: 2020-05-22T12:13:21.571Z
        active:
          type: boolean
          example: true
        code:
          type: string
          example: CONS
        description:
          type: string
          example: Consultoria
        externalId:
          type: string
          example: Cons
        serviceGroupUpperId:
          type: string
    Service-Groups-Integration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
          example: 02285a7b-de5e-460b-a19f-29ae81e1e3cb
        createdAt:
          type: string
          example: 2020-05-22T12:13:21.571Z
        updatedAt:
          type: string
          example: 2020-05-22T12:13:21.571Z
        active:
          type: boolean
          example: true
        code:
          type: string
          example: CONS
        description:
          type: string
          example: Consultoria
        externalId:
          type: string
          example: Cons
        serviceGroupUpperId:
          type: string
tags:
- name: APP2
  description: Ambiente APP2
- name: integration
  description: ""
