---
openapi: 3.0.2
info:
  title: payment-term-customer-permission-integrationV1
  version: 1.0.0
  description: |
    API de integração do vinculo de condição de pagamento e cliente (Payment-Term-Customer-Permission) V1

    Compatível com a versão V11 do serviço de negócio Sales
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Payment-Term-Customer-Permission
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_FullResponse'
          description: Returns a list of Payment-Term-Customer-Permission
        401:
          description: Unauthorized
      summary: Listar condições de pagamento por cliente
      description: Retorna uma lista de vínculos de condições de pagamento e clientes
        cadastrados ou determinados vínculos com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyCreate'
      tags:
        - Payment-Term-Customer-Permission
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            default: minimum
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            oneOf:
              - $ref: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyCreate'
              - $ref: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyUpsert'
              - $ref: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyDelete'
            discriminator:
              mapping:
                create: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyCreate'
                update: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyUpdate'
                upsert: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyUpsert'
                delete: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_BodyDelete'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Payment-Term-Customer-Permission-Integration_V1_FullResponse'
          description: Returns a payment term customer permission register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar Payment-Term-Customer-Permission
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;

        **delete** - Realiza a operação de DELETE do cadastro específicado no header **Integration-Filter**;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: sales'
        schema:
          default: sales
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: payment-term-customer-permission-integration'
        schema:
          default: payment-term-customer-permission-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Payment-Term-Customer-Permission-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Payment-Term-Customer-Permission-Integration_V1_BodyCreate:
      required:
        - externalId
        - paymentTermId
        - customerId
        - customerName
      type: object
      properties:
        externalId:
          description: Código único do registro do cliente no sistema externo
          type: string
          example: 30DIAS#CLI00202
        customerId:
          format: UUID
          description: Identificador do cliente no CRM
          type: string
          example: 5636f630-2358-4cf4-a290-2ec0b13ea47c
        customerName:
          description: Nome do cliente
          type: string
          example: Cliente 00202
        paymentTermId:
          format: UUID
          description: Identificador da condição de pagamento no CRM
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
    Payment-Term-Customer-Permission-Integration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
          example: 30DIAS#CLI00202
        customerId:
          format: UUID
          type: string
          example: 5636f630-2358-4cf4-a290-2ec0b13ea47c
        customerName:
          type: string
          example: Cliente 00202
        paymentTermId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
    Payment-Term-Customer-Permission-Integration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
          example: 30DIAS#CLI00202
        customerId:
          format: UUID
          type: string
          example: 5636f630-2358-4cf4-a290-2ec0b13ea47c
        customerName:
          type: string
          example: Cliente 00202
        paymentTermId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
    Payment-Term-Customer-Permission-Integration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
          example: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        externalId:
          type: string
          example: 30DIAS#CLI00202
        customerId:
          format: UUID
          type: string
          example: 5636f630-2358-4cf4-a290-2ec0b13ea47c
        customerName:
          type: string
          example: Cliente 00202
        paymentTermId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
    Payment-Term-Customer-Permission-Integration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
          example: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        externalId:
          type: string
          example: 30DIAS#CLI00202
        customerId:
          format: UUID
          type: string
          example: 5636f630-2358-4cf4-a290-2ec0b13ea47c
        customerName:
          type: string
          example: Cliente 00202
        paymentTermId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
    Payment-Term-Customer-Permission-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createdAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Payment-Term-Customer-Permission-Integration_V1_BodyDelete:
      description: No body
      type: object
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
