---
openapi: 3.0.2
info:
  title: exchange-rates-integrationV1
  version: 1.0.0
  description: |
    API de integração de cotação de conversão de moedas (Exchange rates) V1

    Compatível com a versão de negócio Administration V9
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Exchange-rates
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exchange-ratesIntegration_V1_FullResponse'
          description: Returns a list of exchange rates
        401:
          description: Unauthorized
      summary: Listar Exchange Rates
      description: Retorna uma lista de cotações cadastradas ou determinadas cotações
        com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Exchange-ratesIntegration_V1_BodyCreate'
      tags:
        - Exchange-rates
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            anyOf:
              - $ref: '#/components/schemas/Exchange-ratesIntegration_V1_BodyCreate'
              - $ref: '#/components/schemas/Exchange-ratesIntegration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Exchange-ratesIntegration_V1_BodyUpsert'
            discriminator:
              mapping:
                create: '#/components/schemas/Exchange-ratesIntegration_V1_BodyCreate'
                update: '#/components/schemas/Exchange-ratesIntegration_V1_BodyUpdate'
                upsert: '#/components/schemas/Exchange-ratesIntegration_V1_BodyUpsert'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Exchange-ratesIntegration_V1_FullResponse'
          description: Returns a Exchange-rates register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar cotações de conversão de moeda
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: administration'
        schema:
          default: administration
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: Exchange-rates-integration'
        schema:
          default: exchange-rates-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Exchange-ratesIntegration_V1_BodyEmpty:
      description: No body
      type: object
    Exchange-ratesIntegration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Exchange-ratesIntegration_V1_BodyCreate:
      required:
        - currency
        - exchangeCurrency
        - date
        - value
        - externalId
      type: object
      properties:
        date:
          description: Data da conversão
          type: string
        currency:
          description: Moeda a ser convertida
          type: object
          properties:
            id:
              type: string
        exchangeCurrency:
          description: Moeda de comparação para a conversão
          type: object
          properties:
            id:
              type: string
        value:
          description: 'Valor da conversão '
          type: number
        externalId:
          description: Código do sistema externo, identificador único do registro
          type: string
      example:
        date: 2018-02-01
        currency:
          id: 4d782b25-1331-4d50-8081-256804cdb888
        exchangeCurrency:
          id: 4d782b25-1331-4d50-8081-256804ert85g
        value: 3.89
        externalId: BRL-ADL2018-02-01
    Exchange-ratesIntegration_V1_BodyUpdate:
      type: object
      properties:
        date:
          type: string
        currency:
          type: object
          properties:
            id:
              type: string
        exchangeCurrency:
          type: object
          properties:
            id:
              type: string
        value:
          type: number
        externalId:
          type: string
      example:
        date: 2018-02-01
        currency:
          id: 4d782b25-1331-4d50-8081-256804cdb888
        exchangeCurrency:
          id: 4d782b25-1331-4d50-8081-256804ert85g
        value: 3.89
        externalId: BRL-ADL2018-02-01
    Exchange-ratesIntegration_V1_BodyUpsert:
      type: object
      properties:
        date:
          type: string
        currency:
          type: object
          properties:
            id:
              type: string
        exchangeCurrency:
          type: object
          properties:
            id:
              type: string
        value:
          type: number
        externalId:
          type: string
      example:
        date: 2018-02-01
        currency:
          id: 4d782b25-1331-4d50-8081-256804cdb888
        exchangeCurrency:
          id: 4d782b25-1331-4d50-8081-256804ert85g
        value: 3.89
        externalId: BRL-ADL2018-02-01
    Exchange-ratesIntegration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        date:
          type: string
        currency:
          type: object
          properties:
            id:
              type: string
        exchangeCurrency:
          type: object
          properties:
            id:
              type: string
        value:
          type: number
        externalId:
          type: string
      example:
        id: 5d782b25-1331-4d50-8081-256804cdb889
        createdAt: 2018-02-01T00:00:00.000Z
        updatedAt: 2018-02-01T00:00:00.000Z
        date: 2018-02-01
        currency:
          id: 4d782b25-1331-4d50-8081-256804cdb888
        exchangeCurrency:
          id: 4d782b25-1331-4d50-8081-256804ert85g
        value: 3.89
        externalId: BRL-ADL2018-02-01
    Exchange-ratesIntegration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        date:
          type: string
        currency:
          type: object
          properties:
            id:
              type: string
        exchangeCurrency:
          type: object
          properties:
            id:
              type: string
        value:
          type: number
        externalId:
          type: string
      example:
        id: 5d782b25-1331-4d50-8081-256804cdb889
        createdAt: 2018-02-01T00:00:00.000Z
        updatedAt: 2018-02-01T00:00:00.000Z
        date: 2018-02-01
        currency:
          id: 4d782b25-1331-4d50-8081-256804cdb888
        exchangeCurrency:
          id: 4d782b25-1331-4d50-8081-256804ert85g
        value: 3.89
        externalId: BRL-ADL2018-02-01
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
