---
openapi: 3.0.2
info:
  title: order-types-integrationV1
  version: 1.0.0
  description: |
    API de integração de tipo de ordem (Order types) V1

    Compatível com a versão V11 do serviço de negócio Sales
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Order-Types
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order-TypesIntegration_V1_FullResponse'
          description: Returns a list of Order Types
        401:
          description: Unauthorized
      summary: Listar tipos de ordem
      description: Retorna uma lista de tipos de ordem cadastradas ou determinadas
        tipos de ordem com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order-TypesIntegration_V1_BodyCreate'
      tags:
        - Order-Types
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            default: minimum
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            oneOf:
              - $ref: '#/components/schemas/Order-TypesIntegration_V1_BodyCreate'
              - $ref: '#/components/schemas/Order-TypesIntegration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Order-TypesIntegration_V1_BodyUpsert'
            discriminator:
              mapping:
                create: '#/components/schemas/Order-TypesIntegration_V1_BodyCreate'
                update: '#/components/schemas/Order-TypesIntegration_V1_BodyUpdate'
                upsert: '#/components/schemas/Order-TypesIntegration_V1_BodyUpsert'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order-TypesIntegration_V1_FullResponse'
          description: Returns a order type register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar tipos de ordem
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: sales'
        schema:
          default: sales
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: order-types-integration'
        schema:
          default: order-types-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Order-TypesIntegration_V1_BodyEmpty:
      description: No body
      type: object
    Order-TypesIntegration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Order-TypesIntegration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalId:
          type: string
        active:
          type: boolean
        code:
          type: string
        deleted:
          description: ""
          type: boolean
        standard:
          description: ""
          type: boolean
        availableFirstOrder:
          type: boolean
        description:
          description: ""
          type: string
        acronym:
          type: string
      example:
        id: c71c1a24-2300-4d0f-9343-544483df6616
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        active: true
        deleted: false
        standard: false
        externalId: PV
        availableFirstOrder: true
        description: Pedido de venda
        acronym: PV
        code: PV
    Order-TypesIntegration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalId:
          type: string
        active:
          type: boolean
        code:
          type: string
        deleted:
          description: ""
          type: boolean
        standard:
          description: ""
          type: boolean
        availableFirstOrder:
          type: boolean
        description:
          description: ""
          type: string
        acronym:
          type: string
      example:
        id: c71c1a24-2300-4d0f-9343-544483df6616
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        active: true
        deleted: false
        standard: false
        externalId: PV
        availableFirstOrder: true
        description: Pedido de venda
        acronym: PV
        code: PV
    Order-TypesIntegration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
        active:
          type: boolean
        code:
          type: string
        deleted:
          description: ""
          type: boolean
        standard:
          description: ""
          type: boolean
        availableFirstOrder:
          type: boolean
        description:
          description: ""
          type: string
        acronym:
          type: string
      example:
        active: true
        standard: false
        externalId: PV
        deleted: false
        availableFirstOrder: true
        description: Pedido de venda
        acronym: PV
        code: PV
    Order-TypesIntegration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
        active:
          type: boolean
        code:
          type: string
        deleted:
          description: ""
          type: boolean
        standard:
          description: ""
          type: boolean
        availableFirstOrder:
          type: boolean
        description:
          description: ""
          type: string
        acronym:
          type: string
      example:
        active: true
        standard: false
        externalId: PV
        deleted: false
        availableFirstOrder: true
        description: Pedido de venda
        acronym: PV
        code: PV
    Order-TypesIntegration_V1_BodyCreate:
      required:
        - externalId
        - standard
        - description
        - active
        - availableFirstOrder
      type: object
      properties:
        externalId:
          description: Código único no sistema externo para o registro
          type: string
        active:
          description: Indica se o registro está ativo ou inativo
          type: boolean
        code:
          description: Código do tipo de ordem
          type: string
        availableFirstOrder:
          description: Indica se o tipo deve estar disponível na primeira ordem
          type: boolean
        deleted:
          description: Indica se o registro está marcado como removido
          type: boolean
        description:
          description: Descrição do tipo de ordem
          type: string
        acronym:
          description: Siga do tipo de ordem
          type: string
        standard:
          description: Indica se o registro é o padrão a ser utilizado ou não
          type: boolean
      example:
        active: true
        standard: false
        externalId: PV
        deleted: false
        availableFirstOrder: true
        description: Pedido de venda
        acronym: PV
        code: PV
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
