---
openapi: 3.0.2
info:
  title: measurement-units-integrationV1
  version: 1.0.0
  description: |
    API de integração de unidade de medida (Measurement Units) V1

    Compatível com a versão V9 do serviço de negócio Administration
  contact: { }
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Measurement-units
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement-Units-Integration_V1_FullResponse'
          description: Returns a list of measurement units
        401:
          description: Unauthorized
      summary: Listar measurement units
      description: Retorna uma lista de unidades de medida cadastradas ou determinadas
        unidades de medida com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Measurement-Units-Integration_V1_BodyCreate'
      tags:
        - Measurement-units
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            default: minimum
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            oneOf:
              - $ref: '#/components/schemas/Measurement-Units-Integration_V1_BodyCreate'
              - $ref: '#/components/schemas/Measurement-Units-Integration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Measurement-Units-Integration_V1_BodyUpsert'
            discriminator:
              mapping:
                create: '#/components/schemas/Measurement-Units-Integration_V1_BodyCreate'
                update: '#/components/schemas/Measurement-Units-Integration_V1_BodyUpdate'
                upsert: '#/components/schemas/Measurement-Units-Integration_V1_BodyUpsert'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Measurement-Units-Integration_V1_FullResponse'
          description: Returns a measurement-units register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar Measurement-Units
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: administration'
        schema:
          default: administration
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: measurement-units-integration'
        schema:
          default: measurement-units-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Measurement-Units-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Measurement-Units-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Measurement-Units-Integration_V1_BodyCreate:
      required:
        - physicalPropertyId
        - physicalPropertyDescription
        - physicalPropertyAcronym
        - active
        - description
        - externalId
        - acronym
        - standard
        - systemDefault
      type: object
      properties:
        externalId:
          description: Código do sistema externo para identificação única do registro
          type: string
        physicalPropertyId:
          description: Identificador da propriedade física
          type: string
        physicalPropertyDescription:
          description: Descrição da propriedade física
          type: object
          properties:
            en-US:
              type: string
            pt-BR:
              type: string
            es-ES:
              type: string
        physicalPropertyAcronym:
          description: Sigla da propriedade física
          type: string
        active:
          description: Define se o registro está ativo
          type: boolean
        description:
          description: Descrição da unidade de medida
          type: string
        acronym:
          description: Sigla da unidade de medida
          type: string
        conversionRate:
          description: Taxa de conversão com relação a unidade de medida padrão
          type: number
        conversionRateUpdated:
          description: Taxa convertida com relação a unidade de medida padrão
          type: number
        standard:
          description: Define se a unidade de medida é a padrão para a propriedade
            física
          type: boolean
        systemDefault:
          description: Define se a unidade de medida é a padrão do sistema
          type: boolean
      example:
        physicalPropertyId: 1b6fe381-6d7a-446a-dc9d-b9b5dfd1fecd
        physicalPropertyDescription:
          en-US: Electric current
          pt-BR: Corrente elétrica
          es-ES: Corriente eléctrica
        physicalPropertyAcronym: I
        active: true
        externalId: Watts
        description: Watts
        acronym: WT
        conversionRate: 220
        conversionRateUpdated: 220
        standard: false
        systemDefault: false
    Measurement-Units-Integration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
        physicalPropertyId:
          type: string
        physicalPropertyDescription:
          type: object
          properties:
            en-US:
              type: string
            pt-BR:
              type: string
            es-ES:
              type: string
        physicalPropertyAcronym:
          type: string
        active:
          type: boolean
        description:
          type: string
        acronym:
          type: string
        conversionRate:
          type: number
        conversionRateUpdated:
          type: number
        standard:
          type: boolean
        systemDefault:
          type: boolean
      example:
        physicalPropertyId: 1b6fe381-6d7a-446a-dc9d-b9b5dfd1fecd
        physicalPropertyDescription:
          en-US: Electric current
          pt-BR: Corrente elétrica
          es-ES: Corriente eléctrica
        physicalPropertyAcronym: I
        active: true
        externalId: Watts
        description: Watts
        acronym: WT
        conversionRate: 220
        conversionRateUpdated: 220
        standard: false
        systemDefault: false
    Measurement-Units-Integration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
        physicalPropertyId:
          type: string
        physicalPropertyDescription:
          type: object
          properties:
            en-US:
              type: string
            pt-BR:
              type: string
            es-ES:
              type: string
        physicalPropertyAcronym:
          type: string
        active:
          type: boolean
        description:
          type: string
        acronym:
          type: string
        conversionRate:
          type: number
        conversionRateUpdated:
          type: number
        standard:
          type: boolean
        systemDefault:
          type: boolean
      example:
        physicalPropertyId: 1b6fe381-6d7a-446a-dc9d-b9b5dfd1fecd
        physicalPropertyDescription:
          en-US: Electric current
          pt-BR: Corrente elétrica
          es-ES: Corriente eléctrica
        physicalPropertyAcronym: I
        active: true
        externalId: Watts
        description: Watts
        acronym: WT
        conversionRate: 220
        conversionRateUpdated: 220
        standard: false
        systemDefault: false
    Measurement-Units-Integration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalId:
          type: string
        physicalPropertyId:
          type: string
        physicalPropertyDescription:
          type: object
          properties:
            en-US:
              type: string
            pt-BR:
              type: string
            es-ES:
              type: string
        physicalPropertyAcronym:
          type: string
        active:
          type: boolean
        description:
          type: string
        acronym:
          type: string
        conversionRate:
          type: number
        conversionRateUpdated:
          type: number
        standard:
          type: boolean
        systemDefault:
          type: boolean
      example:
        id: 5d6fe381-6d7a-446a-dc9d-b9b5dfd1fece
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        physicalPropertyId: 1b6fe381-6d7a-446a-dc9d-b9b5dfd1fecd
        physicalPropertyDescription:
          en-US: Electric current
          pt-BR: Corrente elétrica
          es-ES: Corriente eléctrica
        physicalPropertyAcronym: I
        active: true
        externalId: Watts
        description: Watts
        acronym: WT
        conversionRate: 220
        conversionRateUpdated: 220
        standard: false
        systemDefault: false
    Measurement-Units-Integration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        externalId:
          type: string
        physicalPropertyId:
          type: string
        physicalPropertyDescription:
          type: object
          properties:
            en-US:
              type: string
            pt-BR:
              type: string
            es-ES:
              type: string
        physicalPropertyAcronym:
          type: string
        active:
          type: boolean
        description:
          type: string
        acronym:
          type: string
        conversionRate:
          type: number
        conversionRateUpdated:
          type: number
        standard:
          type: boolean
        systemDefault:
          type: boolean
      example:
        id: 5d6fe381-6d7a-446a-dc9d-b9b5dfd1fece
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        physicalPropertyId: 1b6fe381-6d7a-446a-dc9d-b9b5dfd1fecd
        physicalPropertyDescription:
          en-US: Electric current
          pt-BR: Corrente elétrica
          es-ES: Corriente eléctrica
        physicalPropertyAcronym: I
        active: true
        externalId: Watts
        description: Watts
        acronym: WT
        conversionRate: 220
        conversionRateUpdated: 220
        standard: false
        systemDefault: false
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
