---
openapi: 3.0.2
info:
  title: product-Groups-integrationV1
  version: 1.0.0
  description: |
    API de integração de grupos de produto (Product Groups) V1

    Compatível com a versão de negócio Product V7
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    summary: API de integração groups
    get:
      tags:
        - Product-Groups
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsIntegration_V1_FullResponse'
          description: Returns a list of product groups
        401:
          description: Unauthorized
      summary: Listar grupo de produtos
      description: Retorna uma lista de grupos de produto cadastrados ou determinados
        grupos com base nos filtros do header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupsIntegration_V1_BodyCreate'
      tags:
        - Product-groups
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            anyOf:
              - $ref: '#/components/schemas/GroupsIntegration_V1_BodyCreate'
              - $ref: '#/components/schemas/GroupsIntegration_V1_BodyUpdate'
              - $ref: '#/components/schemas/GroupsIntegration_V1_BodyUpsert'
            discriminator:
              mapping:
                create: '#/components/schemas/GroupsIntegration_V1_BodyCreate'
                update: '#/components/schemas/GroupsIntegration_V1_BodyUpdate'
                upsert: '#/components/schemas/GroupsIntegration_V1_BodyUpsert'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupsIntegration_V1_FullResponse'
          description: Returns a product group register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar grupos de produto
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: product'
        schema:
          default: product
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: groups-integration'
        schema:
          default: groups-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    GroupsIntegration_V1_BodyEmpty:
      description: No body
      type: object
    GroupsIntegration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    GroupsIntegration_V1_BodyCreate:
      required:
        - active
        - description
        - saleAvailable
        - externalId
      type: object
      properties:
        active:
          description: Define se o registro está ativo
          type: boolean
        code:
          description: Código do grupo de produto
          type: string
        description:
          description: Descrição do grupo de produto
          type: string
        externalId:
          description: Código do sistema externo para identificação única do registro
          type: string
        productGroupUpper:
          description: Grupo de produto superior
          type: object
          properties:
            id:
              type: string
            description:
              type: string
        saleAvailable:
          description: Indica se o grupo de produto deve estar disponível na ordem
            de venda
          type: boolean
      example:
        active: true
        code: "2020"
        description: Eletrônicos
        externalId: ELETRONICOS
        productGroupUpper:
          id: 69f4a626-6510-4159-941c-4ea5fa7bb432
          description: Tecnologia
        saleAvailable: true
    GroupsIntegration_V1_BodyUpdate:
      type: object
      properties:
        active:
          type: boolean
        code:
          type: string
        description:
          type: string
        externalId:
          type: string
        productGroupUpper:
          type: object
          properties:
            id:
              type: string
            description:
              type: string
        saleAvailable:
          type: boolean
      example:
        active: true
        code: "2020"
        description: Eletrônicos
        externalId: ELETRONICOS
        productGroupUpper:
          id: 69f4a626-6510-4159-941c-4ea5fa7bb432
          description: Tecnologia
        saleAvailable: true
    GroupsIntegration_V1_BodyUpsert:
      type: object
      properties:
        active:
          type: boolean
        code:
          type: string
        description:
          type: string
        externalId:
          type: string
        productGroupUpper:
          type: object
          properties:
            id:
              type: string
            description:
              type: string
        saleAvailable:
          type: boolean
      example:
        active: true
        code: "2020"
        description: Eletrônicos
        externalId: ELETRONICOS
        productGroupUpper:
          id: 69f4a626-6510-4159-941c-4ea5fa7bb432
          description: Tecnologia
        saleAvailable: true
    GroupsIntegration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        active:
          type: boolean
        code:
          type: string
        description:
          type: string
        externalId:
          type: string
        productGroupUpper:
          $ref: '#/components/schemas/GroupsIntegration_V1_FullResponse'
          properties:
            id:
              type: string
            description:
              type: string
        saleAvailable:
          type: boolean
      example:
        id: 02285a7b-de5e-460b-a19f-29ae81e1e3cb,
        createdAt: 2020-05-22T12:13:21.571Z,
        updatedAt: 2020-05-22T20:40:32.815Z,
        active: true
        code: "2020"
        description: Eletrônicos
        externalId: ELETRONICOS
        productGroupUpper:
          id: 69f4a626-6510-4159-941c-4ea5fa7bb432
          description: Tecnologia
        saleAvailable: true
    GroupsIntegration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        active:
          type: boolean
        code:
          type: string
        description:
          type: string
        externalId:
          type: string
        productGroupUpper:
          $ref: '#/components/schemas/GroupsIntegration_V1_FullResponse'
          properties:
            id:
              type: string
            description:
              type: string
        saleAvailable:
          type: boolean
      example:
        id: 02285a7b-de5e-460b-a19f-29ae81e1e3cb,
        createdAt: 2020-05-22T12:13:21.571Z,
        updatedAt: 2020-05-22T20:40:32.815Z,
        active: true
        code: "2020"
        description: Eletrônicos
        externalId: ELETRONICOS
        productGroupUpper:
          id: 69f4a626-6510-4159-941c-4ea5fa7bb432
          description: Tecnologia
        saleAvailable: true
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
