---
openapi: 3.0.2
info:
  title: region-companies-integrationV1
  version: 1.0.0
  description: |
    API de integração do vínculo de times e vendedores para definir os responsáveis pela carteira. (Region-Companies) V1

    Compatível com a versão de negócio Accounts V4
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Region-companies
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region-CompaniesIntegration_V1_FullResponse'
          description: Returns a list of regions companies
        401:
          description: Unauthorized
      summary: Listar Region-Companies
      description: Retorna uma lista de vinculos entre times e empresas/filiais ou
        determinados vínculos com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Region-CompaniesIntegration_V1_BodyEmpty'
      tags:
        - Region-companies
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            anyOf:
              - $ref: '#/components/schemas/Region-CompaniesIntegration_V1_BodyCreate'
              - $ref: '#/components/schemas/Region-CompaniesIntegration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Region-CompaniesIntegration_V1_BodyUpsert'
              - $ref: '#/components/schemas/Region-CompaniesIntegration_V1_BodyDelete'
            discriminator:
              mapping:
                create: '#/components/schemas/Region-CompaniesIntegration_V1_BodyCreate'
                update: '#/components/schemas/Region-CompaniesIntegration_V1_BodyUpdate'
                upsert: '#/components/schemas/Region-CompaniesIntegration_V1_BodyUpsert'
                delete: '#/components/schemas/Region-CompaniesIntegration_V1_BodyDelete'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region-CompaniesIntegration_V1_FullResponse'
                discriminator:
                  mapping:
                    full: '#/components/schemas/Region-CompaniesIntegration_V1_FullResponse'
                    minimum: '#/components/schemas/Region-CompaniesIntegration_V1_MinimumResponse'
          description: Returns a Region Company register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar region companies
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;

        **delete** - Realiza a operação de DELETE do cadastro enviado. Deve ser enviado ID do registro
        no header **Integration-Filter** para que o registro seja deletado;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: accounts'
        schema:
          default: accounts
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: region-companies-integration'
        schema:
          default: region-companies-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Region-CompaniesIntegration_V1_BodyEmpty:
      description: No body
      type: object
    Region-CompaniesIntegration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Region-CompaniesIntegration_V1_BodyDelete:
      type: object
    Region-CompaniesIntegration_V1_BodyCreate:
      required:
        - companyId
        - region
        - externalId
      type: object
      properties:
        companyId:
          description: Identificador da empresa/filial da carteira
          type: boolean
        region:
          description: Identificador do time (carteira)
          type: object
          properties:
            id:
              type: string
        externalId:
          description: Código do sistema externo para identificação única do registro
          type: string
      example:
        companyId: 407d9c36-f792-4811-9e59-2d3c2fd392af
        region:
          id: 54ca77f1-3f47-48de-8137-522bfee02252
        externalId: T3|D MG|196100|1|C
    Region-CompaniesIntegration_V1_BodyUpdate:
      type: object
      properties:
        companyId:
          type: boolean
        region:
          type: object
          properties:
            id:
              type: string
        externalId:
          type: string
      example:
        companyId: 407d9c36-f792-4811-9e59-2d3c2fd392af
        region:
          id: 54ca77f1-3f47-48de-8137-522bfee02252
        externalId: T3|D MG|196100|1|C
    Region-CompaniesIntegration_V1_BodyUpsert:
      type: object
      properties:
        companyId:
          type: boolean
        region:
          type: object
          properties:
            id:
              type: string
        externalId:
          type: string
      example:
        companyId: 407d9c36-f792-4811-9e59-2d3c2fd392af
        region:
          id: 54ca77f1-3f47-48de-8137-522bfee02252
        externalId: T3|D MG|196100|1|C
    Region-CompaniesIntegration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        companyId:
          type: boolean
        region:
          type: object
          properties:
            id:
              type: string
        externalId:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        companyId: 407d9c36-f792-4811-9e59-2d3c2fd392af
        region:
          id: 54ca77f1-3f47-48de-8137-522bfee02252
        externalId: T3|D MG|196100|1|C
    Region-CompaniesIntegration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        companyId:
          type: boolean
        region:
          type: object
          properties:
            id:
              type: string
        externalId:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        companyId: 407d9c36-f792-4811-9e59-2d3c2fd392af
        region:
          id: 54ca77f1-3f47-48de-8137-522bfee02252
        externalId: T3|D MG|196100|1|C
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
