---
openapi: 3.0.2
info:
  title: product-inventories-integrationV1
  version: 1.0.0
  description: |
    API de integração de estoque de produto (Product-inventories) V1

    Compatível com a versão de negócio Product V7
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Product-inventories
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product-inventories-Integration_V1_FullResponse'
          description: Returns a list of product inventories
        401:
          description: Unauthorized
      summary: Listar estoque de produtos
      description: Retorna uma lista de estoque de produtos cadastrados ou determinados
        estoques de produtos com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product-inventories-Integration_V1_BodyCreate'
      tags:
        - Product-inventories
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            anyOf:
              - $ref: '#/components/schemas/Product-inventories-Integration_V1_BodyCreate'
              - $ref: '#/components/schemas/Product-inventories-Integration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Product-inventories-Integration_V1_BodyUpsert'
              - $ref: '#/components/schemas/Product-inventories-Integration_V1_BodyDelete'
            discriminator:
              mapping:
                create: '#/components/schemas/Product-inventories-Integration_V1_BodyCreate'
                update: '#/components/schemas/Product-inventories-Integration_V1_BodyUpdate'
                upsert: '#/components/schemas/Product-inventories-Integration_V1_BodyUpsert'
                delete: '#/components/schemas/Product-inventories-Integration_V1_BodyDelete'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product-inventories-Integration_V1_FullResponse'
          description: Returns a product inventories register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar estoque de produtos
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;


        **delete** - Realiza a operação de DELETE do cadastro enviado. Obrigatório informar o ID do
        registro no header **Integration-Filter** e não deve-se enviar nenhum Body;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: product'
        schema:
          default: product
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: product-inventories-integration'
        schema:
          default: product-inventories-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Product-inventories-Integration_V1_BodyDelete:
      description: No body
      type: object
    Product-inventories-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Product-inventories-Integration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
          example: PRODUTO#1#ESTOQUE
        productId:
          format: UUID
          type: string
          example: 9a0c23a7-c94a-4565-a66d-e26b96369b29
        quantity:
          type: number
          example: 10
        companyId:
          format: UUID
          type: string
          example: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyTradingName:
          type: string
          example: D MG 001 - T3
      example:
        externalId: PRODUTO#1#ESTOQUE
        productId: 9a0c23a7-c94a-4565-a66d-e26b96369b29eles
        quantity: 10
        companyId: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyTradingName: D MG 001 - T3
    Product-inventories-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createdAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Product-inventories-Integration_V1_BodyCreate:
      required:
        - productId
        - companyId
        - externalId
        - companyName
      type: object
      properties:
        externalId:
          description: Código do sistema externo para identificar este registro como
            único.
          type: string
          example: PRODUTO#1#ESTOQUE
        productId:
          format: UUID
          description: Identificador do produto no CRM
          type: string
          example: 9a0c23a7-c94a-4565-a66d-e26b96369b29
        quantity:
          description: Quantidade em estoque do produto
          type: number
          example: 10
        companyId:
          format: UUID
          description: Identificador da empresa/filial
          type: string
          example: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyName:
          description: Nome da empresa/filial
          type: string
          example: D MG 001 - T3
        companyTradingName:
          description: Nome fantasia da empresa/filial
          type: string
          example: CD Minas 001
      example:
        externalId: PRODUTO#1#ESTOQUE
        productId: 9a0c23a7-c94a-4565-a66d-e26b96369b29eles
        quantity: 10
        companyId: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyName: D MG 001 - T3
        companyTradingName: CD Minas 001
    Product-inventories-Integration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
          example: PRODUTO#1#ESTOQUE
        productId:
          format: UUID
          type: string
          example: 9a0c23a7-c94a-4565-a66d-e26b96369b29
        quantity:
          type: number
          example: 10
        companyId:
          format: UUID
          type: string
          example: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyName:
          type: string
          example: D MG 001 - T3
        companyTradingName:
          type: string
          example: CD Minas 001
      example:
        externalId: PRODUTO#1#ESTOQUE
        productId: 9a0c23a7-c94a-4565-a66d-e26b96369b29eles
        quantity: 10
        companyId: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyTradingName: CD Minas 001
        companyName: D MG 001 - T3
    Product-inventories-Integration_V1_FullResponse:
      type: object
      properties:
        id:
          type: string
          example: 5cb9b2fc-6004-4f30-a45b-451ca49321ed
        createdAt:
          type: string
          example: 2020-07-13T22:54:11.73Z
        updatedAt:
          type: string
          example: 2020-07-13T22:54:11.73Z
        externalId:
          type: string
          example: PRODUTO#1#ESTOQUE
        productId:
          format: UUID
          type: string
          example: 9a0c23a7-c94a-4565-a66d-e26b96369b29
        quantity:
          type: number
          example: 10
        companyId:
          format: UUID
          type: string
          example: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyName:
          description: Nome da empresa/filial
          type: string
          example: D MG 001 - T3
        companyTradingName:
          type: string
          example: CD Minas 001
      example:
        id: 5cb9b2fc-6004-4f30-a45b-451ca49321ed
        createdAt: 2020-07-13T22:54:11.73Z
        updatedAt: 2020-07-13T22:54:11.73Z
        externalId: PRODUTO#1#ESTOQUE
        productId: 9a0c23a7-c94a-4565-a66d-e26b96369b29eles
        quantity: 10
        companyId: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyName: D MG 001 - T3
        companyTradingName: CD Minas 001
    Product-inventories-Integration_V1_GetResponse:
      type: object
      properties:
        id:
          type: string
          example: 5cb9b2fc-6004-4f30-a45b-451ca49321ed
        createdAt:
          type: string
          example: 2020-07-13T22:54:11.73Z
        updatedAt:
          type: string
          example: 2020-07-13T22:54:11.73Z
        externalId:
          type: string
          example: PRODUTO#1#ESTOQUE
        productId:
          format: UUID
          type: string
          example: 9a0c23a7-c94a-4565-a66d-e26b96369b29
        quantity:
          type: number
          example: 10
        companyId:
          format: UUID
          type: string
          example: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyName:
          description: Nome da empresa/filial
          type: string
          example: D MG 001 - T3
        companyTradingName:
          type: string
          example: CD Minas 001
      example:
        id: 5cb9b2fc-6004-4f30-a45b-451ca49321ed
        createdAt: 2020-07-13T22:54:11.73Z
        updatedAt: 2020-07-13T22:54:11.73Z
        externalId: PRODUTO#1#ESTOQUE
        productId: 9a0c23a7-c94a-4565-a66d-e26b96369b29eles
        quantity: 10
        companyId: 206f58df-5442-40f1-bae7-1a2b984164c5
        companyName: D MG 001 - T3
        companyTradingName: CD Minas 001
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
