---
openapi: 3.0.2
info:
  title: price-list-customer-permission-integrationV1
  version: 1.0.0
  description: |
    API de integração de vínculo de tabela de preço com cliente (Price-list-customer-permission) V1

    Compatível com a versão de negócio Product V7
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Price-List-Customer-Permission
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_FullResponse'
          description: Returns a list of price lists
        401:
          description: Unauthorized
      summary: Listar vinculos de tabela de preço com cliente
      description: Retorna uma lista de vínculos de tabelas de preço e clientes cadastrados
        ou determinadas vínculos com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyCreate'
      tags:
        - Price-List-Customer-Permission
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            anyOf:
              - $ref: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyCreate'
              - $ref: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyUpsert'
              - $ref: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyDelete'
            discriminator:
              mapping:
                create: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyCreate'
                update: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyUpdate'
                upsert: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyUpsert'
                delete: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_BodyDelete'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price-List-Customer-Permission-Integration_V1_FullResponse'
          description: Returns a price list customer permission register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar vínculos de tabelas de preço e cliente
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header **Integration-Action**:

        **create** - Realiza a operação de POST do cadastro enviado;

        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro preenchido no header **Integration-Filter**;

        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for enviado o ID do registro no header **Integration-Filter**;

        **delete** - Realiza a operação de DELETE do cadastro baseado no ID do registro, informado no header **Integration-Filter**;
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: product'
        schema:
          default: product
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: price-list-customer-permission-integration'
        schema:
          default: price-list-customer-permission-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Price-List-Customer-Permission-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Price-List-Customer-Permission-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Price-List-Customer-Permission-Integration_V1_BodyCreate:
      required:
        - priceListId
        - customerId
        - customerName
        - externalId
      type: object
      properties:
        externalId:
          description: Código externo único para o registro
          type: string
          example: PRICELIST#1#CUSTOMER#2555
        priceListId:
          format: UUID
          description: Identificador da tabela de preço
          type: string
          example: 0099e73f-e6e5-4117-810a-4ed630a93b02
        customerId:
          format: UUID
          description: Identificador do cliente
          type: string
          example: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName:
          description: Nome do cliente
          type: string
          example: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
      example:
        priceListId: 0099e73f-e6e5-4117-810a-4ed630a93b02
        externalId: PRICELIST#1#CUSTOMER#2555
        customerId: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
    Price-List-Customer-Permission-Integration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
          example: PRICELIST#1#CUSTOMER#2555
        priceListId:
          format: UUID
          type: string
          example: 0099e73f-e6e5-4117-810a-4ed630a93b02
        customerId:
          format: UUID
          type: string
          example: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName:
          type: string
          example: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
      example:
        priceListId: 0099e73f-e6e5-4117-810a-4ed630a93b02
        externalId: PRICELIST#1#CUSTOMER#2555
        customerId: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
    Price-List-Customer-Permission-Integration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
          example: PRICELIST#1#CUSTOMER#2555
        priceListId:
          format: UUID
          type: string
          example: 0099e73f-e6e5-4117-810a-4ed630a93b02
        customerId:
          format: UUID
          type: string
          example: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName:
          type: string
          example: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
      example:
        priceListId: 0099e73f-e6e5-4117-810a-4ed630a93b02
        externalId: PRICELIST#1#CUSTOMER#2555
        customerId: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
    Price-List-Customer-Permission-Integration_V1_GetResponse:
      type: object
      properties:
        id:
          format: UUID
          type: string
          example: 4b3e19b9-5978-4ae5-8710-3c5cb7a48c43
        createdAt:
          type: string
          example: 2020-10-29T13:42:14.891Z
        updatedAt:
          type: string
          example: 2020-10-29T13:42:14.891Z
        externalId:
          type: string
          example: PRICELIST#1#CUSTOMER#2555
        priceListId:
          format: UUID
          type: string
          example: 0099e73f-e6e5-4117-810a-4ed630a93b02
        customerId:
          format: UUID
          type: string
          example: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName:
          type: string
          example: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
      example:
        id: 4b3e19b9-5978-4ae5-8710-3c5cb7a48c43
        createdAt: 2020-10-29T13:42:14.891Z
        updatedAt: 2020-10-29T13:42:14.891Z
        priceListId: 0099e73f-e6e5-4117-810a-4ed630a93b02
        externalId: PRICELIST#1#CUSTOMER#2555
        customerId: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
    Price-List-Customer-Permission-Integration_V1_FullResponse:
      type: object
      properties:
        id:
          format: UUID
          type: string
          example: 4b3e19b9-5978-4ae5-8710-3c5cb7a48c43
        createdAt:
          type: string
          example: 2020-10-29T13:42:14.891Z
        updatedAt:
          type: string
          example: 2020-10-29T13:42:14.891Z
        externalId:
          type: string
          example: PRICELIST#1#CUSTOMER#2555
        priceListId:
          format: UUID
          type: string
          example: 0099e73f-e6e5-4117-810a-4ed630a93b02
        customerId:
          format: UUID
          type: string
          example: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName:
          type: string
          example: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
      example:
        id: 4b3e19b9-5978-4ae5-8710-3c5cb7a48c43
        createdAt: 2020-10-29T13:42:14.891Z
        updatedAt: 2020-10-29T13:42:14.891Z
        priceListId: 0099e73f-e6e5-4117-810a-4ed630a93b02
        externalId: PRICELIST#1#CUSTOMER#2555
        customerId: f101c590-5ad6-4c8e-88de-b0060ea49295
        customerName: AAAAADRIANA ROSA JÉSSICA CARVALHO LTDA
    Price-List-Customer-Permission-Integration_V1_BodyDelete:
      description: No body
      type: object
tags:
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
