---
openapi: 3.0.2
info:
  title: credit-limits-integrationV1
  version: 1.0.1
  description: |
    API de integração de limite de crédito (Credit-limits) V1

    Compatível com a versão V7, V8 do serviço de negócio Financial
  contact: {}
servers:
  - url: https://{url}/api/{version}/integration
    description: TotvsCRM APP Integration Router Server
    variables:
      url:
        default: totvscrm.app
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
  - url: https://{url}/api/{version}/integration
    description: APP2 Integration Router Server
    variables:
      url:
        default: app2.mastercrm.ws
        description: URL de acesso ao Integration-Router
      version:
        default: v1
        description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
        - Credit-Limits
      parameters:
        - name: Integration-Filter
          description: |
            Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
            RestQuery.
            
            
            Se o header for omitido, lista todos os registros
            
            Se o header não contiver valores, lista todos os registros
          schema:
            type: string
          in: header
          required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Credit-Limits-Integration_V1_FullResponse'
          description: Returns a list of credit-limits
        401:
          description: Unauthorized
      summary: Listar credit limits
      description: Retorna uma lista de limites de crédito cadastradas ou determinados
        limites com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credit-Limits-Integration_V1_BodyCreate'
      tags:
        - Credit-Limits
      parameters:
        - name: Integration-Filter
          description: |
            Filtro do registro específico para a ação. Deve-se usar o identificador principal da
            entidade (ID).
          schema:
            type: string
          in: header
          required: false
        - name: Integration-Response
          description: |
            Nível de detalhe do retorno da API. São suportados atualmente:
            
            **full** - Resposta completa, equivalente a um GET no recurso
            
            **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
            registro
            
            Se o header não for informado, por padrão o retorno será equivalente ao nível
            **minimum**
          schema:
            default: minimum
            enum:
              - full
              - minimum
            type: string
          in: header
          required: false
        - name: Integration-Action
          description: |
            Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
            body da requisição.
          schema:
            oneOf:
              - $ref: '#/components/schemas/Credit-Limits-Integration_V1_BodyCreate'
              - $ref: '#/components/schemas/Credit-Limits-Integration_V1_BodyUpdate'
              - $ref: '#/components/schemas/Credit-Limits-Integration_V1_BodyUpsert'
              - $ref: '#/components/schemas/Credit-Limits-Integration_V1_BodyDelete'
            discriminator:
              mapping:
                create: '#/components/schemas/Credit-Limits-Integration_V1_BodyCreate'
                update: '#/components/schemas/Credit-Limits-Integration_V1_BodyUpdate'
                upsert: '#/components/schemas/Credit-Limits-Integration_V1_BodyUpsert'
                delete: '#/components/schemas/Credit-Limits-Integration_V1_BodyDelete'
          in: header
          required: true
      responses:
        200:
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Credit-Limits-Integration_V1_FullResponse'
                  - $ref: '#/components/schemas/Credit-Limits-Integration_V1_MinimumResponse'
                discriminator:
                  mapping:
                    full: '#/components/schemas/Credit-Limits-Integration_V1_FullResponse'
                    minimum: '#/components/schemas/Credit-Limits-Integration_V1_MinimumResponse'
          description: Returns a credit-limits register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar credit limits
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:


        **create** - Realiza a operação de POST do cadastro enviado;


        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;


        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;

        **delete** - Realiza a operação de DELETE do cadastro enviado com base no ID informado no header **Integration-Filter**
    parameters:
      - name: Integration-Service
        description: 'Serviço responsável pela entidade. Exemplo: financial'
        schema:
          default: financial
          type: string
        in: header
        required: true
      - name: Integration-Resource
        description: 'Recurso para requisição. Exemplo: credit-limits-integration'
        schema:
          default: credit-limits-integration
          type: string
        in: header
        required: true
      - name: Integration-Version
        description: 'Versão da API de integração. Exemplo: v1'
        schema:
          default: v1
          type: string
        in: header
        required: true
components:
  schemas:
    Credit-Limits-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Credit-Limits-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Credit-Limits-Integration_V1_BodyCreate:
      required:
        - externalId
        - customerId
        - active
        - totalValue
        - startDate
        - endDate
      type: object
      properties:
        externalId:
          description: Identificador do sistema externo
          type: string
          example: LIM#30
        active:
          description: Situação do limite de crédito
          type: boolean
          example: true
        companyId:
          format: UUID
          description: Identificador do registro de empresa/filial
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
        companyName:
          description: Nome da empresa/filial
          type: string
          example: WS
        customerId:
          format: UUID
          description: Identificador do cliente
          type: string
          example: 03372773-7b2d-41ae-823d-ffbaf9b79cf4
        customerName:
          description: Nome do cliente
          type: string
          example: José das Neves
        totalValue:
          description: Valor total do limite de crédito
          type: number
          example: 200
        availableValue:
          description: Valor disponível de limite de crédito
          type: number
          example: 100
        startDate:
          format: date
          description: Data inicial de validade do limite de crédito
          type: string
          example: 2020-10-01
        endDate:
          format: date
          description: Data final de validade do limite de crédito
          type: string
          example: 2020-12-01
        note:
          description: Observação do limite de crédito
          type: string
          example: Observação do limite
    Credit-Limits-Integration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
          example: LIM#30
        active:
          type: boolean
          example: true
        companyId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
        companyName:
          type: string
          example: WS
        customerId:
          format: UUID
          type: string
          example: 03372773-7b2d-41ae-823d-ffbaf9b79cf4
        customerName:
          type: string
          example: José das Neves
        totalValue:
          type: number
          example: 200
        availableValue:
          type: number
          example: 100
        startDate:
          format: date
          type: string
          example: 2020-10-01
        endDate:
          format: date
          type: string
          example: 2020-12-01
        note:
          type: string
          example: Observação do limite
    Credit-Limits-Integration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
          example: LIM#30
        active:
          type: boolean
          example: true
        companyId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
        companyName:
          type: string
          example: WS
        customerId:
          format: UUID
          type: string
          example: 03372773-7b2d-41ae-823d-ffbaf9b79cf4
        customerName:
          type: string
          example: José das Neves
        totalValue:
          type: number
          example: 200
        availableValue:
          type: number
          example: 100
        startDate:
          format: date
          type: string
          example: 2020-10-01
        endDate:
          format: date
          type: string
          example: 2020-12-01
        note:
          type: string
          example: Observação do limite
    Credit-Limits-Integration_V1_FullResponse:
      properties:
        id:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        externalId:
          type: string
          example: LIM#30
        active:
          type: boolean
          example: true
        companyId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
        companyName:
          type: string
          example: WS
        customerId:
          format: UUID
          type: string
          example: 03372773-7b2d-41ae-823d-ffbaf9b79cf4
        customerName:
          type: string
          example: José das Neves
        totalValue:
          type: number
          example: 200
        availableValue:
          type: number
          example: 100
        startDate:
          format: date
          type: string
          example: 2020-10-01
        endDate:
          format: date
          type: string
          example: 2020-12-01
        note:
          type: string
          example: Observação do limite
    Credit-Limits-Integration_V1_GetResponse:
      properties:
        id:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        externalId:
          type: string
          example: LIM#30
        active:
          type: boolean
          example: true
        companyId:
          format: UUID
          type: string
          example: 164eb3b0-e3cd-4a74-b3ec-eb3a87a607c5
        companyName:
          type: string
          example: WS
        customerId:
          format: UUID
          type: string
          example: 03372773-7b2d-41ae-823d-ffbaf9b79cf4
        customerName:
          type: string
          example: José das Neves
        totalValue:
          type: number
          example: 200
        availableValue:
          type: number
          example: 100
        startDate:
          format: date
          type: string
          example: 2020-10-01
        endDate:
          format: date
          type: string
          example: 2020-12-01
        note:
          type: string
          example: Observação do limite
    Credit-Limits-Integration_V1_BodyDelete:
      description: No body
      type: object
tags:
  - name: TotvsCRMAPP
    description: Ambiente TotvsCRM APP
  - name: APP2
    description: Ambiente APP2
  - name: integration
    description: ""
