---
openapi: 3.0.2
info:
  title: action-plan-users-integrationV1
  version: 1.0.0
  description: |
    API de integração de usuários participantes de um plano de ação (Action-Plan-Users) V1

    Compatível com a versão V6 do serviço de negócio Opportunity
  contact: {}
servers:
- url: https://{url}/api/{version}/integration
  description: Integration Router Server
  variables:
    url:
      default: app2.mastercrm.ws
      description: URL de acesso ao Integration-Router
    version:
      default: v1
      description: Versão do Integration-Router
paths:
  /record:
    get:
      tags:
      - Action-Plan-Users
      parameters:
      - name: Integration-Filter
        description: |
          Filtro opcional para realizar a busca de um ou mais registros. Suporta o uso de
          RestQuery.

          Se o header for omitido, lista todos os registros

          Se o header não contiver valores, lista todos os registros
        schema:
          type: string
        in: header
        required: false
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action-Plan-Users-Integration_V1_FullResponse'
          description: Returns a list of action-plan-route-activities
        401:
          description: Unauthorized
      summary: Listar Action-Plan-Users
      description: Retorna uma lista de usuários de um plano de ação cadastradas ou
        determinados usuários com base nos filtros no header Integration-Filter
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyCreate'
      tags:
      - Action-Plan-Users
      parameters:
      - name: Integration-Filter
        description: |
          Filtro do registro específico para a ação. Deve-se usar o identificador principal da
          entidade (ID).
        schema:
          type: string
        in: header
        required: false
      - name: Integration-Response
        description: |
          Nível de detalhe do retorno da API. São suportados atualmente:

          **full** - Resposta completa, equivalente a um GET no recurso

          **minimum** - Resposta mínima, equivalente ao ID, data de criação e atualização do
          registro

          Se o header não for informado, por padrão o retorno será equivalente ao nível
          **minimum**
        schema:
          default: minimum
          enum:
          - full
          - minimum
          type: string
        in: header
        required: false
      - name: Integration-Action
        description: |
          Ação a ser realizada na API de integração. Selecione uma das opções para carregar o
          body da requisição.
        schema:
          oneOf:
          - $ref: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyCreate'
          - $ref: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyUpdate'
          - $ref: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyUpsert'
          - $ref: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyDelete'
          discriminator:
            mapping:
              create: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyCreate'
              update: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyUpdate'
              upsert: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyUpsert'
              delete: '#/components/schemas/Action-Plan-Users-Integration_V1_BodyDelete'
        in: header
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action-Plan-Users-Integration_V1_FullResponse'
                discriminator:
                  mapping:
                    full: '#/components/schemas/Action-Plan-Users-Integration_V1_FullResponse'
                    minimum: '#/components/schemas/Action-Plan-Users-Integration_V1_MinimumResponse'
          description: Returns a action-plan-users register
        401:
          description: Unauthorized
      summary: Criar, atualizar e deletar Action-Plan-Users
      description: |
        A ação a ser realizada no cadastro depende do valor preenchido no header
        **Integration-Action**:

        **create** - Realiza a operação de POST do cadastro enviado;

        **update** - Realiza a operação de PATCH do cadastro enviado, baseado no ID do registro
        preenchido no header **Integration-Filter**;

        **upsert** - Realiza a operação de POST do cadastro enviado se não for enviado ID do registro
        no header **Integration-Filter** **OU** realiza a operação de PUT do cadastro enviado se for
        enviado o ID do registro no header **Integration-Filter**;

        **delete** - Realiza a operação de DELETE do registro especificado no header
        **Integration-Filter**;
    parameters:
    - name: Integration-Service
      description: 'Serviço responsável pela entidade. Exemplo: opportunity'
      schema:
        default: opportunity
        type: string
      in: header
      required: true
    - name: Integration-Resource
      description: 'Recurso para requisição. Exemplo: action-plan-users-integration'
      schema:
        default: action-plan-users-integration
        type: string
      in: header
      required: true
    - name: Integration-Version
      description: 'Versão da API de integração. Exemplo: v1'
      schema:
        default: v1
        type: string
      in: header
      required: true
components:
  schemas:
    Action-Plan-Users-Integration_V1_BodyEmpty:
      description: No body
      type: object
    Action-Plan-Users-Integration_V1_MinimumResponse:
      type: object
      properties:
        id:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
      example:
        id: 19de1e5b-37c8-42c6-a62f-3d7bdd11e994
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
    Action-Plan-Users-Integration_V1_BodyDelete:
      description: No body
      type: object
    Action-Plan-Users-Integration_V1_BodyUpdate:
      type: object
      properties:
        externalId:
          type: string
          example: PLAN1#USER1
        userId:
          format: uuid
          type: string
          example: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId:
          format: uuid
          type: string
          example: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
      example:
        externalId: PLAN1#USER1
        userId: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
    Action-Plan-Users-Integration_V1_BodyUpsert:
      type: object
      properties:
        externalId:
          type: string
          example: PLAN1#USER1
        userId:
          format: uuid
          type: string
          example: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId:
          format: uuid
          type: string
          example: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
      example:
        externalId: PLAN1#USER1
        userId: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
    Action-Plan-Users-Integration_V1_FullResponse:
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        externalId:
          type: string
          example: PLAN1#USER1
        userId:
          format: uuid
          type: string
          example: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId:
          format: uuid
          type: string
          example: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
      example:
        id: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        externalId: PLAN1#USER1
        userId: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
    Action-Plan-Users-Integration_V1_GetResponse:
      type: object
      properties:
        id:
          format: uuid
          type: string
          example: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        createdAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        updatedAt:
          type: string
          example: 2019-08-13T18:00:38.780Z
        externalId:
          type: string
          example: PLAN1#USER1
        userId:
          format: uuid
          type: string
          example: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId:
          format: uuid
          type: string
          example: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
      example:
        id: aabc54a1-49c3-444d-88ec-eaa3fbe63e86
        createAt: 2019-08-13T18:00:38.780Z
        updatedAt: 2019-08-13T18:00:38.780Z
        externalId: PLAN1#USER1
        userId: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
    Action-Plan-Users-Integration_V1_BodyCreate:
      required:
      - externalId
      - userId
      - actionPlanId
      type: object
      properties:
        externalId:
          description: Código único do sistema externo para o registro
          type: string
          example: PLAN1#USER1
        userId:
          format: uuid
          description: Identificador do usuário
          type: string
          example: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId:
          format: uuid
          description: Identificador do plano de ação
          type: string
          example: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
      example:
        externalId: PLAN1#USER1
        userId: 7636f630-2358-4cf4-a290-2ec0b13ea47c
        actionPlanId: 2f25831d-a7ff-4408-bf1e-3595b621fdc2
tags:
- name: APP2
  description: Ambiente APP2
- name: integration
  description: ""
